import React from 'react';
import Icon from '../components/Icon';
import { IconComponent } from '../types';

const Balcony: IconComponent = (props) => (
    <Icon viewBox="0 0 24 24" {...props}>
        <g>
            <path
                fill="none"
                stroke="currentColor"
                strokeWidth={1.5}
                strokeMiterlimit={10}
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M17.8,15.9V8.1c0-3.2-2.6-5.8-5.8-5.8S6.2,4.9,6.2,8.1v7.7"
            />
            <line
                fill="none"
                stroke="currentColor"
                strokeWidth={1.5}
                strokeMiterlimit={10}
                strokeLinecap="round"
                strokeLinejoin="round"
                x1="1"
                y1="15.9"
                x2="23"
                y2="15.9"
            />
            <line
                fill="none"
                stroke="currentColor"
                strokeWidth={1.5}
                strokeMiterlimit={10}
                strokeLinecap="round"
                strokeLinejoin="round"
                x1="12"
                y1="2.3"
                x2="12"
                y2="15.8"
            />
            <line
                fill="none"
                stroke="currentColor"
                strokeWidth={1.5}
                strokeMiterlimit={10}
                strokeLinecap="round"
                strokeLinejoin="round"
                x1="6.2"
                y1="9"
                x2="17.8"
                y2="9"
            />
            <polyline
                fill="none"
                stroke="currentColor"
                strokeWidth={1.5}
                strokeMiterlimit={10}
                strokeLinecap="round"
                strokeLinejoin="round"
                points="2.3,15.9 2.3,21.7 21.7,21.7 21.7,15.9 	"
            />
            <line
                fill="none"
                stroke="currentColor"
                strokeWidth={1.5}
                strokeMiterlimit={10}
                strokeLinecap="round"
                strokeLinejoin="round"
                x1="6.1"
                y1="21.7"
                x2="6.1"
                y2="15.9"
            />
            <line
                fill="none"
                stroke="currentColor"
                strokeWidth={1.5}
                strokeMiterlimit={10}
                strokeLinecap="round"
                strokeLinejoin="round"
                x1="17.8"
                y1="21.7"
                x2="17.8"
                y2="15.9"
            />
            <line
                fill="none"
                stroke="currentColor"
                strokeWidth={1.5}
                strokeMiterlimit={10}
                strokeLinecap="round"
                strokeLinejoin="round"
                x1="10"
                y1="21.7"
                x2="10"
                y2="15.9"
            />
            <line
                fill="none"
                stroke="currentColor"
                strokeWidth={1.5}
                strokeMiterlimit={10}
                strokeLinecap="round"
                strokeLinejoin="round"
                x1="13.9"
                y1="21.7"
                x2="13.9"
                y2="15.9"
            />
        </g>
    </Icon>
);

export default Balcony;
