import React from 'react';
import Icon from '../components/Icon';
import { IconComponent } from '../types';

const HighBathtub: IconComponent = (props) => (
    <Icon viewBox="0 0 24 24" {...props}>
        <g>
            <g>
                <g>
                    <path
                        fill="none"
                        stroke="currentColor"
                        strokeWidth={1.5}
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M4.9,6.9h5.7c0-1.6-1.3-2.8-2.8-2.8S4.9,5.3,4.9,6.9z"
                    />
                    <path
                        fill="none"
                        stroke="currentColor"
                        strokeWidth={1.5}
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M2.3,14.6V3.4c0-1.5,1.2-2.7,2.7-2.7c1.5,0,2.7,1.2,2.7,2.7v0.7"
                    />
                    <path
                        fill="none"
                        stroke="currentColor"
                        strokeWidth={1.5}
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M9.7,9.5V8.8"
                    />
                    <path
                        fill="none"
                        stroke="currentColor"
                        strokeWidth={1.5}
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M7.7,10.8v-0.7"
                    />
                    <path
                        fill="none"
                        stroke="currentColor"
                        strokeWidth={1.5}
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M5.7,9.5V8.8"
                    />
                </g>
            </g>
            <line
                fill="none"
                stroke="currentColor"
                strokeWidth={1.5}
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit={10}
                x1={1}
                y1={14.6}
                x2={23}
                y2={14.6}
            />
            <path
                fill="none"
                stroke="currentColor"
                strokeWidth={1.5}
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit={10}
                d="M21.8,14.6l-1.3,5.7c-0.2,0.9-1,1.5-2,1.5h-13c-0.9,0-1.7-0.6-2-1.5l-1.5-5.7"
            />
            <line
                fill="none"
                stroke="currentColor"
                strokeWidth={1.5}
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit={10}
                x1={18}
                y1={21.8}
                x2={18.8}
                y2={23.3}
            />
            <line
                fill="none"
                stroke="currentColor"
                strokeWidth={1.5}
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit={10}
                x1={5.8}
                y1={21.8}
                x2={5.1}
                y2={23.3}
            />
        </g>
    </Icon>
);

export default HighBathtub;
