import React from 'react';
import Icon from '../components/Icon';
import { IconComponent } from '../types';

const Crutches: IconComponent = (props) => (
    <Icon viewBox="0 0 24 24" {...props}>
        <g>
            <g>
                <path
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeMiterlimit="10"
                    d="M9.2,3.9c0.7,0,1.3-0.6,1.3-1.3S10,1.2,9.2,1.2H4.6c-0.7,0-1.3,0.6-1.3,1.3s0.6,1.3,1.3,1.3H9.2z"
                />
                <path
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeMiterlimit="10"
                    d="M4.7,3.9v6.2c0,1.8,0.8,3.4,2.2,4.4h0C8.2,13.5,9,11.8,9,10.1V3.9"
                />
                <line
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeMiterlimit="10"
                    x1="4.7"
                    y1="9"
                    x2="9"
                    y2="9"
                />
                <path
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeMiterlimit="10"
                    d="M5.4,21.3c0-0.8,0.7-1.5,1.5-1.5s1.5,0.7,1.5,1.5v1.5H5.4V21.3z"
                />
                <line
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeMiterlimit="10"
                    x1="6.8"
                    y1="19.8"
                    x2="6.8"
                    y2="14.5"
                />
            </g>
            <g>
                <path
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeMiterlimit="10"
                    d="M19.4,3.9c0.7,0,1.3-0.6,1.3-1.3s-0.6-1.3-1.3-1.3h-4.6c-0.7,0-1.3,0.6-1.3,1.3s0.6,1.3,1.3,1.3H19.4z"
                />
                <path
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeMiterlimit="10"
                    d="M14.8,3.9v6.2c0,1.8,0.8,3.4,2.2,4.4h0c1.4-1.1,2.2-2.7,2.2-4.4V3.9"
                />
                <line
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeMiterlimit="10"
                    x1="14.8"
                    y1="9"
                    x2="19.2"
                    y2="9"
                />
                <path
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeMiterlimit="10"
                    d="M15.5,21.3c0-0.8,0.7-1.5,1.5-1.5s1.5,0.7,1.5,1.5v1.5h-2.9V21.3z"
                />
                <line
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeMiterlimit="10"
                    x1="17"
                    y1="19.8"
                    x2="17"
                    y2="14.5"
                />
            </g>
        </g>
    </Icon>
);

export default Crutches;
