import React from 'react';
import Icon from '../components/Icon';
import { IconComponent } from '../types';

const JeepCar: IconComponent = (props) => (
    <Icon viewBox="0 0 24 24" {...props}>
        <g>
            <g transform="translate(0.5 0.5)">
                <polyline
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeMiterlimit="10"
                    points="5.8,10.9 3.2,10.9 3.2,16.3 4.9,16.3"
                />
                <line
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeMiterlimit="10"
                    x1="9.3"
                    y1="16.3"
                    x2="16.6"
                    y2="16.3"
                />
                <circle
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeMiterlimit="10"
                    cx="7.1"
                    cy="16.8"
                    r="2.2"
                />
                <circle
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeMiterlimit="10"
                    cx="18.8"
                    cy="16.8"
                    r="2.2"
                />
                <line
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeMiterlimit="10"
                    x1="12.3"
                    y1="4.7"
                    x2="12.3"
                    y2="10.9"
                />
            </g>
            <line
                fill="none"
                stroke="currentColor"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit="10"
                x1="12.8"
                y1="16.8"
                x2="12.8"
                y2="11.4"
            />
            <path
                fill="none"
                stroke="currentColor"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit="10"
                d="M21.5,16.8h1.8v-3.5c0-1-0.8-1.9-1.9-1.9h-2.6H6.3"
            />
            <path
                fill="none"
                stroke="currentColor"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit="10"
                d="M19,11l-2.6-4.8c-0.3-0.6-1-1-1.7-1H6.3c-1,0-1.8,0.6-1.9,1.5l-0.7,4.7"
            />
            <line
                fill="none"
                stroke="currentColor"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit="10"
                x1="8.4"
                y1="5.2"
                x2="8.4"
                y2="11.4"
            />
            <path
                fill="none"
                stroke="currentColor"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit="10"
                d="M3.1,13.5c0,0.7-0.5,1.2-1.2,1.2s-1.2-0.5-1.2-1.2v-3c0-0.7,0.5-1.2,1.2-1.2s1.2,0.5,1.2,1.2V13.5z"
            />
        </g>
    </Icon>
);

export default JeepCar;
