import React from 'react';
import Icon from '../components/Icon';
import { IconComponent } from '../types';

const ShowerSeat: IconComponent = (props) => (
    <Icon viewBox="0 0 24 24" {...props}>
        <g>
            <g>
                <path
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M3,7.5h6.8c0-1.9-1.5-3.4-3.4-3.4S3,5.6,3,7.5z"
                />
                <path
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M1,15.4v-12c0-1.5,1.2-2.7,2.7-2.7c1.5,0,2.7,1.2,2.7,2.7v0.7"
                />
                <path
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M8.5,10.5V9.8"
                />
                <path
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M6.4,11.8v-0.7"
                />
                <path
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M4.4,10.5V9.8"
                />
            </g>
            <g>
                <path
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeMiterlimit="10"
                    d="M19.9,11.5c1.5-0.1,1.2-1.7,1.2-1.7c0-1.6-1.2-1.6-1.2-1.6h-6.3c0,0-1.2,0-1.2,1.6c0,0-0.2,1.6,1.2,1.7H19.9z"
                />
                <path
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeMiterlimit="10"
                    d="M13.2,17.2c0,0-1.1,0.7-1.1,3l-0.2,3.1"
                />
                <path
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeMiterlimit="10"
                    d="M20.4,17.2c0,0,1.1,0.7,1.1,3l0.2,3.1"
                />
                <line
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeMiterlimit="10"
                    x1="14.3"
                    y1="15.4"
                    x2="14.3"
                    y2="11.5"
                />
                <line
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeMiterlimit="10"
                    x1="19.2"
                    y1="15.4"
                    x2="19.2"
                    y2="11.5"
                />
                <path
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeMiterlimit="10"
                    d="M11.4,17.2c-0.5,0-0.9-0.4-0.9-0.9c0-0.5,0.4-0.9,0.9-0.9l10.7,0c0.5,0,0.9,0.4,0.9,0.9c0,0.5-0.4,0.9-0.9,0.9L11.4,17.2z"
                />
            </g>
        </g>
    </Icon>
);

export default ShowerSeat;
